Adds option to add multiple prepare-commit-msg git hooks.

diff --git a/git-templates/hooks/prepare-commit-msg b/git-templates/hooks/prepare-commit-msg
--- a/git-templates/hooks/prepare-commit-msg
+++ b/git-templates/hooks/prepare-commit-msg
@@ -1,30 +1,27 @@
 #!/bin/bash
 #
-# An example hook script to prepare the commit log message.
-# Called by "git commit" with the name of the file that has the
-# commit message, followed by the description of the commit
-# message's source.  The hook's purpose is to edit the commit
-# message file.  If the hook fails with a non-zero status,
-# the commit is aborted.
-#
-# To enable this hook, rename this file to "prepare-commit-msg".
+# This script should be saved in a git repo as a hook file, e.g. .git/hooks/pre-receive.
+# It looks for scripts in the .git/hooks/pre-receive.d directory and executes them in order,
+# passing along stdin. If any script exits with a non-zero status, this script exits.
 
-COMMIT_MSG_FILE=$1
-COMMIT_SOURCE=$2
-SHA1=$3
+script_dir=$(dirname $0)
+hook_name=$(basename $0)
 
-# Only add custom message when there is no commit source
-# ($COMMIT_SOURCE is empty). Otherwise, keep the default message
-# proposed by Git. Possible commit source: message, template,
-# merge, squash or commit. See https://git-scm.com/docs/githooks
-if [[ -z "$COMMIT_SOURCE" ]]
-then
-  ref=$(git rev-parse --abbrev-ref HEAD)
-  if [[ $ref =~ ^.*((YCL|YDI|PAL)-[0-9]+).* ]]
-  then
-    hint=$(cat "$COMMIT_MSG_FILE")
-    ticket="${BASH_REMATCH[1]}"
-    echo "${ticket}: " > "$COMMIT_MSG_FILE"
-    echo "$hint" >> "$COMMIT_MSG_FILE"
-  fi
+hook_dir="$script_dir/$hook_name.d"
+
+if [[ -d $hook_dir ]]; then
+  stdin=$(cat /dev/stdin)
+
+  for hook in $hook_dir/*; do
+    echo "Running $hook_name/$hook hook"
+    echo "$stdin" | $hook "$@"
+
+    exit_code=$?
+
+    if [ $exit_code != 0 ]; then
+      exit $exit_code
+    fi
+  done
 fi
+
+exit 0
